plugins {
	id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT'
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		url 'https://masa.dy.fi/maven'
	}
}

dependencies {
	//to change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "carpet:fabric-carpet:${project.carpet_version}+v${project.carpet_build}"
}

processResources {
	var replaceProperties = [
			minecraft_version	: project.minecraft_version,
			mod_id				: project.archives_base_name,
			mod_version			: version,
			mod_name			: project.mod_name,
			mod_desc			: project.mod_desc,
			mod_authors			: project.mod_authors,
			mod_license			: project.mod_license,
			mod_site			: project.mod_site,
			mod_source			: project.mod_source,
			mod_issues			: project.mod_issues
	]
	inputs.properties replaceProperties

	filesMatching(["fabric.mod.json"]) {
		expand replaceProperties
	}
}

processResources {
	var replaceProperties = [
			java_version		: project.java_version
	]
	inputs.properties replaceProperties

	filesMatching([project.archives_base_name + ".mixins.json"]) {
		expand replaceProperties
	}
}

def targetJavaVersion = project.java_version as Integer
tasks.withType(JavaCompile).configureEach {
	// ensure that the encoding is set to UTF-8, no matter what the system default is
	// this fixes some edge cases with special characters not displaying correctly
	// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
	// If Javadoc is generated, this must be specified in that task too.
	it.options.encoding = "UTF-8"
	if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
		it.options.release.set(targetJavaVersion)
	}
}

java {
	setSourceCompatibility(project.java_version)
	setTargetCompatibility(project.java_version)
}
